spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  cache:
    cache-names: leaderboardCache
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h,recordStats
